# Generated by Django 4.1.7 on 2023-09-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
