# Generated by Django 4.1.7 on 2023-09-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
